Cleaning the cast and crew tables before tableau

In [2]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('moviedb')
df = pd.read_sql('select * from principals p join name n on p.nconst = n.nconst join basics b on b.tconst=p.tconst join ratings r on r.tconst=p.tconst', conn)  ## testing

In [3]:
df.isnull().sum()  ## many primary profesions missing, this column is redundant because we already have "category" so we can drop it later

tconst                  0
ordering                0
nconst                  0
category                0
job                     0
characters              0
nconst                  0
primaryName             0
birthYear               0
deathYear               0
primaryProfession    1495
knownForTitles          0
tconst                  0
titleType               0
primaryTitle            0
originalTitle           0
isAdult                 0
startYear               0
endYear                 0
runtimeMinutes          0
genres                  0
tconst                  0
averageRating           0
numVotes                0
dtype: int64

In [14]:
df.duplicated().sum()
df = df.drop_duplicates() ## there were a few duplicates

In [4]:
df.head(100)

,tconst,ordering,nconst,category,job,characters,nconst,primaryName,birthYear,deathYear,...,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,tconst,averageRating,numVotes
0,tt0000001,2,nm0005690,director,\N,\N,nm0005690,William K.L. Dickson,1860,1935,...,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short",tt0000001,5.6,1694
1,tt0000001,3,nm0374658,cinematographer,director of photography,\N,nm0374658,William Heise,1847,1910,...,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short",tt0000001,5.6,1694
2,tt0000002,1,nm0721526,director,\N,\N,nm0721526,Émile Reynaud,1844,1918,...,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short",tt0000002,6.0,210
3,tt0000003,1,nm0721526,director,\N,\N,nm0721526,Émile Reynaud,1844,1918,...,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance",tt0000003,6.5,1441
4,tt0000004,1,nm0721526,director,\N,\N,nm0721526,Émile Reynaud,1844,1918,...,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short",tt0000004,6.1,122
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,tt0000060,1,nm0005690,director,\N,\N,nm0005690,William K.L. Dickson,1860,1935,...,Dancing Darkies,Dancing Darkies,0,1896,\N,\N,"Documentary,Short",tt0000060,7.7,60
96,tt0000060,2,nm0005658,cinematographer,\N,\N,nm0005658,G.W. Bitzer,1872,1944,...,Dancing Darkies,Dancing Darkies,0,1896,\N,\N,"Documentary,Short",tt0000060,7.7,60
97,tt0000061,2,nm0010291,director,\N,\N,nm0010291,Birt Acres,1854,1918,...,Dancing Girls,Dancing Girls,0,1896,\N,\N,Short,tt0000061,4.1,13
98,tt0000061,3,nm0666972,producer,producer,\N,nm0666972,Robert W. Paul,1869,1943,...,Dancing Girls,Dancing Girls,0,1896,\N,\N,Short,tt0000061,4.1,13
99,tt0000062,1,nm0617588,director,\N,\N,nm0617588,Georges Méliès,1861,1938,...,Danse serpentine,Danse serpentine,0,1896,\N,1,Short,tt0000062,6.5,160

In [5]:
df = df.drop(columns=['ordering', 'isAdult',  'endYear', 'originalTitle', 'characters','ordering','primaryProfession', 'knownForTitles','job','birthYear','deathYear'])
## we dont need these columns

In [6]:
df = df.loc[:, ~df.columns.duplicated(keep='first')]  ## we had 3 copies of tconst and remove 2

In [7]:
df.head(100)

,tconst,nconst,category,primaryName,titleType,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000001,nm0005690,director,William K.L. Dickson,short,Carmencita,1894,1,"Documentary,Short",5.6,1694
1,tt0000001,nm0374658,cinematographer,William Heise,short,Carmencita,1894,1,"Documentary,Short",5.6,1694
2,tt0000002,nm0721526,director,Émile Reynaud,short,Le clown et ses chiens,1892,5,"Animation,Short",6.0,210
3,tt0000003,nm0721526,director,Émile Reynaud,short,Pauvre Pierrot,1892,4,"Animation,Comedy,Romance",6.5,1441
4,tt0000004,nm0721526,director,Émile Reynaud,short,Un bon bock,1892,12,"Animation,Short",6.1,122
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0000060,nm0005690,director,William K.L. Dickson,short,Dancing Darkies,1896,\N,"Documentary,Short",7.7,60
96,tt0000060,nm0005658,cinematographer,G.W. Bitzer,short,Dancing Darkies,1896,\N,"Documentary,Short",7.7,60
97,tt0000061,nm0010291,director,Birt Acres,short,Dancing Girls,1896,\N,Short,4.1,13
98,tt0000061,nm0666972,producer,Robert W. Paul,short,Dancing Girls,1896,\N,Short,4.1,13
99,tt0000062,nm0617588,director,Georges Méliès,short,Danse serpentine,1896,1,Short,6.5,160

In [8]:
df.dtypes
## some of these need to be numeric

tconst             object
nconst             object
category           object
primaryName        object
titleType          object
primaryTitle       object
startYear          object
runtimeMinutes     object
genres             object
averageRating     float64
numVotes            int64
dtype: object

In [9]:
## The data uses /N instead of null which causes errors when trying to convert to numeric
import numpy as np
df['runtimeMinutes'] = df['runtimeMinutes'].replace(r'\N', np.nan)
df['startYear'] = df['startYear'].replace(r'\N', np.nan)

In [10]:
df['runtimeMinutes'] = pd.to_numeric(df['runtimeMinutes'])
df['startYear'] = pd.to_numeric(df['startYear'])

In [12]:
df.dtypes  ## data types are correct now

tconst             object
nconst             object
category           object
primaryName        object
titleType          object
primaryTitle       object
startYear         float64
runtimeMinutes    float64
genres             object
averageRating     float64
numVotes            int64
dtype: object

In [16]:
df.head(100)  ## final look before saving

,tconst,nconst,category,primaryName,titleType,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000001,nm0005690,director,William K.L. Dickson,short,Carmencita,1894.0,1.0,"Documentary,Short",5.6,1694
1,tt0000001,nm0374658,cinematographer,William Heise,short,Carmencita,1894.0,1.0,"Documentary,Short",5.6,1694
2,tt0000002,nm0721526,director,Émile Reynaud,short,Le clown et ses chiens,1892.0,5.0,"Animation,Short",6.0,210
3,tt0000003,nm0721526,director,Émile Reynaud,short,Pauvre Pierrot,1892.0,4.0,"Animation,Comedy,Romance",6.5,1441
4,tt0000004,nm0721526,director,Émile Reynaud,short,Un bon bock,1892.0,12.0,"Animation,Short",6.1,122
...,...,...,...,...,...,...,...,...,...,...,...
95,tt0000060,nm0005690,director,William K.L. Dickson,short,Dancing Darkies,1896.0,NaN,"Documentary,Short",7.7,60
96,tt0000060,nm0005658,cinematographer,G.W. Bitzer,short,Dancing Darkies,1896.0,NaN,"Documentary,Short",7.7,60
97,tt0000061,nm0010291,director,Birt Acres,short,Dancing Girls,1896.0,NaN,Short,4.1,13
98,tt0000061,nm0666972,producer,Robert W. Paul,short,Dancing Girls,1896.0,NaN,Short,4.1,13
99,tt0000062,nm0617588,director,Georges Méliès,short,Danse serpentine,1896.0,1.0,Short,6.5,160

In [17]:
df.to_csv('name_principals_clean.csv')